version = 0.1

# ── App Stack ────────────────────────────────────────────────────────────
[app.deploy.parameters]
stack_name        = "immich-cluster-app"
template_file     = "immich-app-ecs.yaml"
region            = "ap-south-2"
capabilities      = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false

parameter_overrides = [
  "VpcId=vpc-09f10291c29a1a7cf",
  "SubnetIds=subnet-0436d6552c6a53c4f",
  "S3FilesystemId=fs-0cb352e1b01128274",
  "EnvFileS3Arn=arn:aws:s3:::immich-conf-ap-south-2-704678691702/immich.env",
  "HostName=immich.proapplication.net",
  "KeyPair=immich",
  "ImageName=ecr-public.aws.com/<your-alias>/immich/immich-server:release"
]

tags = [
  "Project=immich"
]