version = 0.1

# ── App Stack: API ────────────────────────────────────────────────────────────
[api.deploy.parameters]
stack_name        = "immich-api-prod"
template_file     = "immich-app-ec2.yaml"
region            = "us-east-1"
capabilities      = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false

parameter_overrides = [
  "VpcId=vpc-0ba8dc166b641aa2b",
  "SubnetId=subnet-05827c47b9a6e2a13",  
  "InstanceType=t4g.medium",
  "S3FilesystemId=fs-094e7716463d37e8f",
  "S3FilesSGId=sg-07051e7ea1ac70a0f",
  "AllowedCIDR=0.0.0.0/0",
  "BucketName=immich-media-prod-us-east-1-704678691702",
  "Environment=prod"
]

tags = [
  "Project=immich",
  "Environment=prod",
  "ManagedBy=sam"
]

# ── App Stack: Microservices ──────────────────────────────────────────────────
[microservices.deploy.parameters]
stack_name        = "immich-microservices-prod"
template_file     = "immich-app-ec2.yaml"
region            = "us-east-1"
capabilities      = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false

parameter_overrides = [
  "VpcId=vpc-0ba8dc166b641aa2b",
  "SubnetId=subnet-05827c47b9a6e2a13",  
  "InstanceType=t4g.micro",
  "S3FilesystemId=fs-0de845be2a16d9f00",
    "S3FilesSGId=sg-02538ae581500cb2c",
  "AllowedCIDR=00.0.0.0/0",
  "BucketName=immich-media-prod-us-east-1-704678691702",
  "Environment=prod"
]

tags = [
  "Project=immich",
  "Environment=prod",
  "ManagedBy=sam"
]
