version = 0.1

# ── Supporting Resource Stack ────────────────────────────────────────────────────────────
[sr.deploy.parameters]
stack_name        = "immich-supporting-resources"
template_file     = "immich-sr-ec2.yaml"
region            = "us-east-1"
capabilities      = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false

parameter_overrides = [
  "VpcId=vpc-0ba8dc166b641aa2b",
  "SubnetId=subnet-05827c47b9a6e2a13",  
  "InstanceType=t4g.large",
  "AllowedCIDR=0.0.0.0/0",
  "Environment=prod"
]

tags = [
  "Project=immich",
  "Environment=prod",
  "ManagedBy=sam"
]

# ── App Stack ────────────────────────────────────────────────────────────
[app.deploy.parameters]
stack_name        = "immich-cluster"
template_file     = "immich-ecs-v2-prod.yaml"
region            = "us-east-1"
capabilities      = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false

parameter_overrides = [
  "VpcId=vpc-0ba8dc166b641aa2b",
  "SubnetIds=subnet-05827c47b9a6e2a13",
  "S3FilesystemId=fs-0732676bc2d2d33ff",
  "S3FilesSGId=sg-03c4ba5c577498b91",
  "EnvFileS3Arn=arn:aws:s3:::immich-conf-us-east-1-704678691702/immich.env"
]

tags = [
  "Project=immich",
  "Environment=prod",
  "ManagedBy=sam"
]