AWSTemplateFormatVersion: '2010-09-09'
Description: Immich SSL Security ACM

Parameters:
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: The Route 53 Public Hosted Zone ID for your domain.

  DomainName:
    Type: String
    Description: The fully qualified domain name for the application (e.g., app.yourdomain.com).

Resources:
  ACMCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

Outputs:
  ACMCertificateARN:
    Value: !Ref ACMCertificate