version = 0.1

# ── Cache Stack ───────────────────────────────────────────────────────────────
[sd.deploy.parameters]
stack_name        = "immich-service-discovery"
template_file     = "immich-sd-ec2.yaml"
region            = "us-east-1"
capabilities      = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false

parameter_overrides = [
  "VpcId=vpc-02cab24e4cec51cb5",
  "SubnetId=subnet-0f05fbb3404eabb19",
  "BucketName=immich-conf-us-east-1-704678691702",
  "ImageLocationS3Uri=s3://immich-conf-us-east-1-704678691702/images",
  "InstanceType=t4g.micro"
]

tags = [
  "Project=immich"
]
