version = 0.1

# ── EC2 Stack ───────────────────────────────────────────────────────────────
[sd.deploy.parameters]
stack_name        = "immich-service-discovery"
template_file     = "immich-sd-ec2.yaml"
region            = "ap-south-1"
capabilities      = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false

parameter_overrides = [
  "VpcId=vpc-0d58eaa3d2dd95593",
  "SubnetId=subnet-0cb74cba8880e488e",
  "BucketName=immich-conf-ap-south-1-704678691702",
  "ImageLocationS3Uri=s3://immich-conf-ap-south-1-704678691702/images",
  "InstanceType=t4g.small",
  "CronScriptsS3URI=s3://immich-conf-ap-south-1-704678691702/scripts",
  "EnvFileS3URI=s3://immich-conf-ap-south-1-704678691702/immich.env",
  "HostedZoneId=Z0716017FNQSL38BA6TG",
  "DomainName=immich.proapplication.net",
  "CloudFrontPrefixListId=pl-9aa247f3",
  "ACMCertificate=arn:aws:acm:us-east-1:704678691702:certificate/a641cacf-b3e2-49d3-9104-fe4ce5820d77"
]

tags = [
  "Project=immich"
]

# ── ACM Stack ───────────────────────────────────────────────────────────────
[acm.deploy.parameters]
stack_name        = "immich-service-discovery-cert"
template_file     = "immich-sd-acm.yaml"
region            = "us-east-1"
capabilities      = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false

parameter_overrides = [
  "HostedZoneId=Z0716017FNQSL38BA6TG",
  "DomainName=immich.proapplication.net"
]

tags = [
  "Project=immich"
]
