version = 0.1
# ── Storage Stack ─────────────────────────────────────────────────────────────
[storage.deploy.parameters]
stack_name        = "immich-storage-s3"
template_file     = "immich-storage-s3.yaml"
region            = "ap-south-1"
capabilities      = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false

parameter_overrides = [
  "VpcId=vpc-0d58eaa3d2dd95593",
  "SubnetId=subnet-0cb74cba8880e488e",
  "BucketName=immich-media",
  "IntelligentTieringDays=15",
]

tags = [
  "Project=immich"
]

# ── Config Stack ─────────────────────────────────────────────────────────────
[conf.deploy.parameters]
stack_name        = "immich-conf-s3"
template_file     = "immich-conf-s3.yaml"
region            = "ap-south-1"
capabilities      = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false

parameter_overrides = [
  "BucketName=immich-conf"
]

tags = [
  "Project=immich"
]