version = 0.1
# ── Storage Stack ─────────────────────────────────────────────────────────────
[storage.deploy.parameters]
stack_name        = "immich-storage-s3-prod"
template_file     = "immich-storage-s3.yaml"
region            = "us-east-1"
capabilities      = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false

parameter_overrides = [
  "VpcId=vpc-0ba8dc166b641aa2b",
  "SubnetId=subnet-05827c47b9a6e2a13",
  "BucketName=immich-media",
  "IntelligentTieringDays=60",
  "Environment=prod"
]

tags = [
  "Project=immich",
  "Environment=prod",
  "ManagedBy=sam"
]

# ── Config Stack ─────────────────────────────────────────────────────────────
[conf.deploy.parameters]
stack_name        = "immich-conf-s3-prod"
template_file     = "immich-conf-s3.yaml"
region            = "us-east-1"
capabilities      = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false

parameter_overrides = [
  "BucketName=immich-conf"
]

tags = [
  "Project=immich",
  "Environment=prod",
  "ManagedBy=sam"
]