version = 0.1
# ── Storage Stack ─────────────────────────────────────────────────────────────
[vpc.deploy.parameters]
stack_name        = "immich-vpc"
template_file     = "immich-vpc.yaml"
region            = "ap-south-1"
capabilities      = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false

parameter_overrides = [
  "VPCName=immich-vpc",
  "VPCRegion=ap-south-1",
  "NatGatewayRequired=false",
  "HostedZoneName=immich.internal"
]

tags = [
  "Project=immich",
]
