version = 0.1
# ── Lambda Stack ─────────────────────────────────────────────────────────────────
[composer.deploy.parameters]
stack_name        = "immich-composer-handler"
template_file     = "immich-composer-handlers.yaml"
region            = "ap-south-2"
capabilities      = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
resolve_s3 = true

parameter_overrides = [
  "SpotLaunchTemplateId=lt-03dc06539a177caa1",
  "VolumeId=vol-0cf3e9a98f1b471e8",
  "HostedZoneId=Z02289381ARPAOGOTJFBT",               # Tighten this to your actual VPC CIDR
  "RecordName=backend.ap-south-2.immich.internal",
  "ECSClusterName=immich-cluster",
  "ECSServiceNames=immich-api-service"
]

# Tags applied to all resources in the stack
tags = [
  "Project=immich"
]